### ISSUE TITLE
Some models are not loaded correctly

### ISSUE THREAD

**Issue by omar00070** [itslebi/GDDraco#2]
Hey thanks for the project, this is exactly what I am looking for because I wanna load glb models from the internet where they are usually compressed using draco, issue I see is that some models are not loaded correctly

examples added

<img width="809" height="582" alt="Image" src="https://github.com/user-attachments/assets/d605957c-c33b-4310-afd6-341409cb4580" />

the model is supposed to look like this

<img width="1110" height="803" alt="Image" src="https://github.com/user-attachments/assets/b29de980-0d9f-4990-afb4-2bf115855108" />

**Comment by itslebi** [comment]
@omar00070 can you share the model with me so that I can understand why it does not work? It may be using a data format internally that I currrently do not support in the extension and it would be really helpful.

Also, please make sure you are using the lastes release from 4 days ago as there were lots of bugs that were fixed and most of the code was rewritten.
[Link to release](https://github.com/itslebi/GDDraco/releases/tag/v4.5-patch2)

**Comment by omar00070** [comment]
I've tried the latest release, here is an example 
https://drive.google.com/file/d/1p5-6oxo3l3bkAj-lHi7JymzGD5Ch7W1q/view?usp=sharing

I could try to share more if you'd like

**Comment by itslebi** [comment]
Thank you for the model that is very helpful. I belive the issue is the TANGENT attribute which the extension does not support at the moment. I will try to add support for it over the next week.

You can see that warning on the terminal:
<img width="954" height="75" alt="Image" src="https://github.com/user-attachments/assets/fed7572c-351c-4465-a2e9-474936f254ab" />

**Comment by omar00070** [comment]
ohh great, I would love to help by unfortunately my cpp knowledge is 0, if anything I will try and see if I could make the fix, if not I will wait for you, thanks a lot for the extension btw

**Comment by itslebi** [comment]
@omar00070 I belive I have fixed the issue. Try the new release and let me know if you find anything else.

<img width="830" height="531" alt="Image" src="https://github.com/user-attachments/assets/908aa9dc-1170-4e7f-a9fd-87ee80cdd25b" />

**Comment by omar00070** [comment]
thanks, tested my library of models, and it looks like most of them are working perfectly now, however I still have some instances that are not working perfectly
model https://drive.google.com/file/d/17OuJjLwwW46UjLrfAxhdbXdZs5ad8rqR/view?usp=drive_link

GDDraco
<img width="878" height="780" alt="Image" src="https://github.com/user-attachments/assets/034cccee-4224-451f-84d3-04e968eeb1f3" />


should be

<img width="783" height="685" alt="Image" src="https://github.com/user-attachments/assets/506662cc-0d16-4bde-b809-ad8d7c1a15b3" />

**Comment by omar00070** [comment]
also this model has some weird artifacts
model https://drive.google.com/file/d/1uCuDhzB4p1Eg2iyUqc0v_HEE_rAf2MDg/view?usp=sharing

GDDraco

<img width="997" height="798" alt="Image" src="https://github.com/user-attachments/assets/86e2f509-62d4-4892-8fa1-f117a7ad05e5" />

should be
<img width="808" height="562" alt="Image" src="https://github.com/user-attachments/assets/30ee38eb-8bdd-40df-9ebb-2b9fcce1e7ad" />

**Comment by itslebi** [comment]
Thank you for the detailed description. I am going to look into it again and I will update you once I fix it.

**Comment by omar00070** [comment]
happy to help!

**Comment by itslebi** [comment]
@omar00070  I have identified the issue with the table still need to figure out how to fix it without breaking the importer for other meshes (it has to do with material cull mode, you can manually change it to front on the meantime). 
On the bed model, it appears fine on my scene, it may have to do with specific lighting. Could you plese tell me which version of godot you are using (windows/linux and v.4.5 or v.4.4...) also if you could share with the specific light/world setup you have on that scene so that I can see if it is being caused by the Tangent and how I can resolve it.

<img width="1050" height="425" alt="Image" src="https://github.com/user-attachments/assets/6f84943d-0ff6-4583-b943-a102055a1903" />

**Comment by omar00070** [comment]
I am using the latest godot version 4.5.1, the macos one, I use mac M3, the world is the basic, no lighting added actually, I've just checked a new scene and you are right, the object fine there actually, only the table is missing now

btw do you have discord?

**Comment by itslebi** [comment]
Good news I think I figured out what is wrong with the table (will make a commit soon after some more testing). Also, thank you for the information on the godot version, I did not test the linux build I provide and I wanted to know if it was that the problem.

As of discord, i did not have a server but I am planning on making some more godot extensions so here is an invite to one [https://discord.gg/chtXjK8f](https://discord.gg/chtXjK8f). Feel free to chat there or send me a DM!
